

GET https://8q5zg2p8tj.us-east-1.awsapprunner.com/odata/v4/order/OrderData?$filter=created_at%20ge%202025-09-11T00:00:00Z%20and%20created_at%20lt%202025-09-12T00:00:00Z
Headers:
  Content-Type: application/json
